// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Phone() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<svg width=\"17\" height=\"17\" viewBox=\"0 0 17 17\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" class=\"flex-grow-0 flex-shrink-0\" preserveAspectRatio=\"none\"><path fill=\"#323232\" d=\"M1.24586 3.02816L3.31379 0.962136C3.45966 0.815619 3.63305 0.699367 3.82398 0.620059C4.01492 0.540751 4.21964 0.49995 4.42639 0.5C4.84775 0.5 5.24386 0.665049 5.54094 0.962136L7.76615 3.18738C7.91267 3.33325 8.02891 3.50664 8.10822 3.69758C8.18753 3.88852 8.22833 4.09325 8.22828 4.3C8.22828 4.72136 8.06323 5.11748 7.76615 5.41456L6.13899 7.04175C6.51987 7.88128 7.04942 8.64503 7.70207 9.29612C8.35309 9.95037 9.11676 10.4818 9.95641 10.865L11.5836 9.23786C11.7294 9.09135 11.9028 8.9751 12.0938 8.89579C12.2847 8.81648 12.4894 8.77568 12.6962 8.77573C13.1175 8.77573 13.5136 8.94078 13.8107 9.23786L16.0379 11.4612C16.1846 11.6073 16.3009 11.781 16.3802 11.9723C16.4595 12.1636 16.5002 12.3687 16.5 12.5757C16.5 12.9971 16.335 13.3932 16.0379 13.6903L13.9738 15.7544C13.5 16.2301 12.8457 16.5 12.1739 16.5C12.0321 16.5 11.8962 16.4883 11.7622 16.465C9.14477 16.034 6.54869 14.6417 4.45358 12.5485C2.36041 10.4573 0.970136 7.86311 0.533249 5.23786C0.401212 4.43592 0.667228 3.61068 1.24586 3.02816V3.02816Z\"></path></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func WhitePhone() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<svg width=\"20\" height=\"21\" viewBox=\"0 0 20 21\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" class=\"flex-grow-0 flex-shrink-0\" preserveAspectRatio=\"none\"><path d=\"M1.24375 3.89531L3.73984 1.40156C3.91592 1.22471 4.1252 1.08439 4.35567 0.988665C4.58614 0.892938 4.83325 0.84369 5.08281 0.84375C5.59141 0.84375 6.06953 1.04297 6.42812 1.40156L9.11406 4.0875C9.29091 4.26358 9.43123 4.47286 9.52696 4.70333C9.62269 4.9338 9.67193 5.18091 9.67187 5.43047C9.67187 5.93906 9.47266 6.41719 9.11406 6.77578L7.15 8.73984C7.60974 9.75319 8.24893 10.675 9.03672 11.4609C9.82253 12.2506 10.7443 12.8922 11.7578 13.3547L13.7219 11.3906C13.898 11.2138 14.1072 11.0735 14.3377 10.9777C14.5682 10.882 14.8153 10.8328 15.0648 10.8328C15.5734 10.8328 16.0516 11.032 16.4102 11.3906L19.0984 14.0742C19.2755 14.2506 19.4159 14.4603 19.5117 14.6912C19.6074 14.9221 19.6565 15.1696 19.6562 15.4195C19.6562 15.9281 19.457 16.4062 19.0984 16.7648L16.607 19.2562C16.0352 19.8305 15.2453 20.1562 14.4344 20.1562C14.2633 20.1562 14.0992 20.1422 13.9375 20.1141C10.7781 19.5938 7.64453 17.9133 5.11562 15.3867C2.58906 12.8625 0.910936 9.73125 0.383593 6.5625C0.224218 5.59453 0.545312 4.59844 1.24375 3.89531V3.89531Z\" fill=\"white\"></path></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
