// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Twitter() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<svg width=\"31\" height=\"24\" viewBox=\"0 0 31 24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" class=\"flex-grow-0 flex-shrink-0\" preserveAspectRatio=\"none\"><path d=\"M30.5 3.22269C29.3766 3.69218 28.185 4.00035 26.9649 4.13696C28.2358 3.41836 29.2116 2.28045 29.6711 0.924632C28.463 1.60098 27.1412 2.0775 25.7628 2.33362C24.64 1.20521 23.0405 0.5 21.2702 0.5C17.8711 0.5 15.1152 3.09975 15.1152 6.30622C15.1152 6.76136 15.1696 7.20446 15.2745 7.62953C10.1593 7.38731 5.62414 5.07577 2.5884 1.56285C2.05871 2.42041 1.7552 3.41792 1.7552 4.48188C1.7552 6.49637 2.84188 8.2735 4.49328 9.31479C3.51588 9.28591 2.55998 9.03687 1.70539 8.58846C1.70504 8.61278 1.70504 8.63711 1.70504 8.66154C1.70504 11.4748 3.8266 13.8216 6.64215 14.355C5.7358 14.5875 4.78511 14.6216 3.8627 14.4545C4.64586 16.7613 6.91895 18.4399 9.61215 18.4869C7.5057 20.0441 4.85176 20.9724 1.96824 20.9724C1.47137 20.9724 0.981523 20.9449 0.5 20.8913C3.22379 22.5387 6.45898 23.5 9.93477 23.5C21.2559 23.5 27.4466 14.6524 27.4466 6.97959C27.4466 6.72775 27.4407 6.47735 27.4288 6.22839C28.6337 5.40663 29.6737 4.38881 30.5 3.22269\" fill=\"white\"></path></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
