root = "."
testdata_dir = "testdata"
tmp_dir = "build"

[build]
  cmd = "make templ-clean && go build -o build/app ./cmd/app && curl http://localhost:9999/trigger"
  args_bin = []
  bin = "./build/app"
  delay = 0
  exclude_dir = ["build", "public/styles", "public/uploads", "node_modules", "testdata", "cmd/utils", "bin"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*_templ.go", ".*_templ.txt"]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "templ", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false
  post_cmd = ["make templ-clean && kill -15 $(lsof -ti:3000)"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = true
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true
  keep_scroll = true