// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func Call(phoneNumber string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_Call_105f`,
		Function: `function __templ_Call_105f(phoneNumber){if(/Mobi|Android/i.test(navigator.userAgent)) 
        return window.location.href= ` + "`" + `tel:${phoneNumber}` + "`" + `
    CopyToClipboard(phoneNumber)
}`,
		Call:       templ.SafeScript(`__templ_Call_105f`, phoneNumber),
		CallInline: templ.SafeScriptInline(`__templ_Call_105f`, phoneNumber),
	}
}
