// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func Carousel(id string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_Carousel_f97a`,
		Function: `function __templ_Carousel_f97a(id){let currentSlide = 0;
    const slides = document.querySelectorAll(id);
    slides[currentSlide].classList.remove("hidden");

    function showSlide(n) {
        slides[currentSlide].classList.add("hidden");
        slides[n].classList.remove("hidden");
        currentSlide = n;
    };

    setInterval(() => showSlide((currentSlide + 1) % slides.length), 8000);
}`,
		Call:       templ.SafeScript(`__templ_Carousel_f97a`, id),
		CallInline: templ.SafeScriptInline(`__templ_Carousel_f97a`, id),
	}
}
