// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func Copy(text string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_Copy_3ee3`,
		Function: `function __templ_Copy_3ee3(text){CopyToClipboard(text)
}`,
		Call:       templ.SafeScript(`__templ_Copy_3ee3`, text),
		CallInline: templ.SafeScriptInline(`__templ_Copy_3ee3`, text),
	}
}
