// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Subscribe() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"w-full py-[2vh]\"><div class=\"w-full font-nino font-bold text-4xl text-primary text-center pb-[2vh]\">მიიღე ყველა სიახლე ელფოსტაზე</div><div class=\"w-full flex justify-center my-[4vh]\"><div class=\"shadower w-[50%] relative flex gap-[5px] bg-primary py-[15px] px-5 rounded-lg\"><div class=\"mt-[10px]\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Letter().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><input type=\"email\" placeholder=\"შეიყვანე შენი ელფოსტა\" class=\"pl-4 pr-16 py-2 placeholder-white focus:outline-none w-full bg-primary f-nino w-[300px] text-white\"> <button class=\"rounded-r-lg w-[150px] h-full flex flex-col align-center justify-center absolute right-0 top-0 bg-secondary text-black\"><p class=\"w-full flex justify-center font-nino font-bold mt-[10px]\">გამოწერა</p></button></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
