// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func ChatMin() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"cursor-pointer fixed bottom-[5vh] right-[15vw]\"><svg height=\"200px\" width=\"200px\" version=\"1.1\" id=\"Layer_1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" viewBox=\"0 0 297 297\" xml:space=\"preserve\" fill=\"#000000\"><g id=\"SVGRepo_bgCarrier\" stroke-width=\"0\"></g> <g id=\"SVGRepo_tracerCarrier\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></g> <g id=\"SVGRepo_iconCarrier\"><g><g><circle style=\"fill:#008772;\" cx=\"148.5\" cy=\"148.5\" r=\"148.5\"></circle></g> <path style=\"fill:#008772;\" d=\"M68.489,183.939l110.026,110.026c62.607-12.851,110.838-65.104,117.653-129.706l-67.897-67.897 L68.489,183.939z\"></path> <g><path style=\"fill:#FFF200;\" d=\"M148.5,66c-54.676,0-99,33.243-99,74.25c0,38.177,38.42,69.62,87.843,73.778L132,247.5l16.5-14.514 V66L148.5,66z\"></path> <path style=\"fill:#FFF200;\" d=\"M148.5,66v166.986l23.394-20.577c43.384-7.884,75.606-37.197,75.606-72.159 C247.5,99.243,203.176,66,148.5,66z\"></path></g> <g><g><path style=\"fill:#FFF200;\" d=\"M148.5,66v166.986l23.394-20.577c43.384-7.884,75.606-37.197,75.606-72.159 C247.5,99.243,203.176,66,148.5,66z\"></path></g> <g><circle style=\"fill:#008772;\" cx=\"198\" cy=\"142.5\" r=\"13\"></circle></g> <g><circle style=\"fill:#008772;\" cx=\"148.5\" cy=\"142.5\" r=\"13\"></circle></g> <g><path style=\"fill:#008772;\" d=\"M161.5,142.5c0-7.18-5.82-13-13-13v26C155.68,155.5,161.5,149.68,161.5,142.5z\"></path></g> <g><circle style=\"fill:#008772;\" cx=\"99\" cy=\"142.5\" r=\"13\"></circle></g></g></g></g></svg></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
